name: fluro_annotation_generator
description: >
  Enable annotation support for fluro,
  which automatically generate fluro routes for you.
version: 0.2.1
homepage: https://github.com/copydog/fluro_annotation_generator
author: patrick.z <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: ">=1.2.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: any
  build: any
  source_gen: any
  build_config: any
  fluro: any
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any

flutter:
  uses-material-design: false
